blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://pyloo.readthedocs.io/
    about: Check out the documentation before creating an issue
  - name: 💬 Questions and Discussions
    url: https://github.com/your-username/pyloo/discussions
    about: Please ask and answer questions here
