name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-typecheck:
    name: Linting and Type Checking
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies for linting/typing
      run: |
        python -m pip install --upgrade pip
        # Install core and dev dependencies (assuming flake8/mypy are in dev)
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        # Install the package itself in editable mode
        pip install -e .

    - name: Lint with flake8
      run: |
        flake8 pyloo

    - name: Check types with mypy
      run: |
        mypy pyloo
